import type { Signal } from "../_components/SignalCard";

export const SEED_SIGNALS: Signal[] = [
  {
    id: "1",
    source: "X",
    handle: "@ratchet_ai",
    timeAgo: "2m ago",
    body: "feels like every founder I talk to this week is quietly migrating off the same three vendors. not gonna name names but you know who you are.",
    analyzing: true,
  },
  {
    id: "2",
    source: "REDDIT",
    handle: "u/infra_will",
    context: "r/LocalLLaMA",
    timeAgo: "4m ago",
    body: "Anyone else getting destroyed by Pinecone pricing? We're 14 people, ~200M vectors, just got our bill and I'm seriously considering moving to Qdrant. What am I missing?",
    matches: "Initech win · public reply",
    fitScore: 0.84,
  },
  {
    id: "3",
    source: "HACKER NEWS",
    handle: "throwaway42",
    timeAgo: "13m ago",
    body: "Show HN: We hit the limit on our hosted vector DB and had to rebuild our retrieval layer in a weekend. Here's what we learned about cold-start costs and re-indexing.",
    matches: "retrieval pattern · medium fit",
    fitScore: 0.71,
  },
  {
    id: "4",
    source: "REDDIT",
    handle: "u/ml_engineer",
    context: "r/MachineLearning",
    timeAgo: "22m ago",
    body: "How are people handling the trade-off between hosted convenience and self-hosted cost at scale? We're past the break-even point on our managed vector store and it's not subtle anymore.",
    matches: "ICP signal · founder voice",
    fitScore: 0.82,
  },
  {
    id: "5",
    source: "X",
    handle: "@founderboard",
    timeAgo: "31m ago",
    body: "Quietly stunned at the bill from our \"managed\" vector DB this month. We barely doubled our index. Anyone have honest numbers on what self-hosting Qdrant or Weaviate looks like at 100M+ vectors?",
    matches: "pricing trigger · public reply",
    fitScore: 0.79,
  },
  {
    id: "6",
    source: "HACKER NEWS",
    handle: "siberian_dev",
    timeAgo: "47m ago",
    body: "Ask HN: Is anyone running production retrieval workloads on a single-node Qdrant in 2026, or has it become impossible without sharding? Looking for honest scale stories before we commit.",
    matches: "retrieval pattern",
    fitScore: 0.66,
  },
  {
    id: "7",
    source: "REDDIT",
    handle: "u/aiops_anon",
    context: "r/devops",
    timeAgo: "1h ago",
    body: "Migrated off Pinecone last quarter. The first month of self-hosted was rough — backups, snapshots, a long weekend with PagerDuty — but our infra cost dropped 70% and queries got faster. Worth it for us.",
    matches: "won-deal echo",
    fitScore: 0.58,
  },
  {
    id: "8",
    source: "X",
    handle: "@vector_skeptic",
    timeAgo: "1h ago",
    body: "Hot take: most teams paying $20k/mo for a hosted vector DB could halve that bill by reading their own access logs and tuning their chunk sizes. Almost no one does it.",
    fitScore: 0.41,
  },
  {
    id: "9",
    source: "REDDIT",
    handle: "u/staff_eng_42",
    context: "r/programming",
    timeAgo: "2h ago",
    body: "After three migrations in two years I've concluded the boring answer is: pick the storage layer your team already operates and bolt vector search onto it. The marginal accuracy gain is rarely worth the new on-call surface.",
    matches: "ICP voice match",
    fitScore: 0.74,
  },
  {
    id: "10",
    source: "HACKER NEWS",
    handle: "kobold_dev",
    timeAgo: "3h ago",
    body: "Spent the morning costing out three options for a 500M-vector workload. Hosted runs $48k/mo, self-hosted Qdrant on bare metal pencils to about $9k/mo all-in including ops time. The gap is hard to ignore.",
    matches: "pricing trigger · cost study",
    fitScore: 0.81,
  },
  {
    id: "11",
    source: "X",
    handle: "@ml_lead",
    timeAgo: "4h ago",
    body: "If your retrieval costs more than your inference, you've made a wrong turn somewhere. We had this realization in Q1 and it changed how we picked our entire stack.",
    fitScore: 0.55,
  },
  {
    id: "12",
    source: "REDDIT",
    handle: "u/late_stage_yc",
    context: "r/startups",
    timeAgo: "5h ago",
    body: "Honest question for anyone past Series A: what's the lowest-friction way to get off Pinecone without a multi-week migration? We've outgrown the pricing but every alternative feels like a project.",
    matches: "Initech-pattern · public reply",
    fitScore: 0.86,
  },
];
