// Real draft generator: Gemini Flash Lite via the same API key as cr_agent.
// Pulls grounding evidence from ZE, builds a structured prompt, returns a
// strict JSON { subject, body }. Falls back to a deterministic template if
// the API key is missing or the call fails — the flow never blocks.

import { GoogleGenerativeAI, SchemaType } from "@google/generative-ai";
import {
  getDocumentContent,
  listDocuments,
} from "./zeroentropyClient";
import { extractJsonObject } from "./researchClient";

const GEMINI_TIMEOUT_MS = 20_000;
const MAX_GROUNDING_DOCS = 12;        // cap on how many brand docs to send Gemma
const MAX_GROUNDING_CHARS_PER_DOC = 1_200;
const TOTAL_PROMPT_CAP = 16_000;

const DRAFT_SCHEMA = {
  type: SchemaType.OBJECT,
  properties: {
    subject: { type: SchemaType.STRING },
    body: { type: SchemaType.STRING },
  },
  required: ["subject", "body"],
};

export type SignalInfo = {
  signal_id: string;
  source: string;
  handle: string;
  context?: string;
  body: string;
  contact_name: string;
  contact_role?: string;
  contact_company?: string;
};

export type GeneratedDraft = {
  subject: string;
  body: string;
  evidence: string[];
  source: "gemini" | "fallback";
  fallback_reason?: string;
};

function firstName(full: string): string {
  return (full.split(" ")[0] ?? full).trim() || "there";
}

function shortQuote(body: string, max = 200): string {
  const trimmed = body.replace(/\s+/g, " ").trim();
  if (trimmed.length <= max) return trimmed;
  const cut = trimmed.slice(0, max);
  const space = cut.lastIndexOf(" ");
  return (space > 0 ? cut.slice(0, space) : cut) + "…";
}

function templateDraft(signal: SignalInfo, evidence: string[]): GeneratedDraft {
  const first = firstName(signal.contact_name);
  const quote = shortQuote(signal.body, 140);
  const sourceLabel =
    signal.source === "HACKER NEWS" ? "your HN post" : `your ${signal.source.toLowerCase()} post`;
  const subject =
    /pinecone|vector db|managed vector/i.test(signal.body)
      ? "On the Pinecone math"
      : /soc2|compliance|fintech/i.test(signal.body)
        ? "Compliance question — quick note"
        : /migrate|switching|moving off/i.test(signal.body)
          ? "Migration playbook — saw your post"
          : "Saw your post — one quick thought";
  const body = [
    `${first},`,
    "",
    `Saw ${sourceLabel}: "${quote}"`,
    "",
    "We've seen this pattern a few times — usually the trigger isn't the bill, it's the on-call cost. The math flips fast.",
    "",
    "If a 15-minute look at the numbers would be useful, I can pull a side-by-side from one of our recent migrations. No deck, no demo — just the numbers.",
    "",
    "— our team",
  ].join("\n");
  return { subject, body, evidence, source: "fallback", fallback_reason: "GOOGLE_GENAI_API_KEY not set" };
}

const SYSTEM_PROMPT = `You are a founding-team member writing a cold outreach email.

═══════════════════════════════════════════════════════════════════
WHO YOU ARE — IDENTITY ANCHOR
═══════════════════════════════════════════════════════════════════

Your identity comes from the YOUR COMPANY (FROM WEBSITE) section
below. That section was generated by researching the company's own
website — it is the canonical source of who you are, what you sell,
and how you sign your name.

The sign-off MUST come from this website data — never from any
uploaded supplementary file. The company URL is the source of truth
for the brand identity.

  - Sign-off format: "— <first-name>, <company-name>"
  - Pick the company-name from the website data (it usually appears
    in the one_liner, the description, or in the website URL itself).
  - If the website URL is, e.g., "https://initech.dev", a fine
    company-name is "Initech" (titlecase the domain).
  - Pick a plausible first-name (e.g., the founder's first name if
    visible in the website data; otherwise something neutral).

You are NOT a Burrow employee. Burrow is the platform that surfaced
this lead — the recipient must believe this email came directly
from your company. Never mention Burrow. Never say "we use Burrow"
or "our outreach platform."

═══════════════════════════════════════════════════════════════════
WHO YOU ARE WRITING TO
═══════════════════════════════════════════════════════════════════

The RECIPIENT is a stranger who just posted publicly about a
problem your product solves. They are NOT a customer yet. This is
a cold outreach. Their post is the SIGNAL POST and their identity
is in the RECIPIENT section.

═══════════════════════════════════════════════════════════════════
WHAT TO WRITE
═══════════════════════════════════════════════════════════════════

- Open by referencing the SIGNAL POST in one line. A short literal
  quote is fine — but don't quote more than one sentence, and don't
  open with "I came across your post" or "I saw on Reddit".

- READ ALL the SUPPLEMENTARY CONTEXT docs below. They include past
  wins, lost deals, ICP detail, case studies, and competitor notes.
  Pick the ONE that most directly maps to this specific prospect's
  problem in the SIGNAL POST — not just the closest customer name,
  but the win whose details (industry, scale, pain point, outcome)
  actually mirror what the prospect is venting about.
- In ONE sentence, cite that ONE win with a concrete number
  (customer name + the specific metric from the doc). If genuinely
  no win in the docs fits the situation, anchor on a concrete ICP
  or brand-voice point instead — but the bar is "does this map to
  THIS prospect", not "is this our most impressive win".

- In ONE sentence, make the pitch — what your company does, in the
  prospect's own language from the signal post. Concrete numbers,
  no marketing slop ("solutions", "leverage", "unlock",
  "revolutionary" — banned).

- Close with a single ask: a 15-minute call OR a specific
  deliverable ("a side-by-side cost breakdown of your current setup
  vs. ours", "the migration playbook we used with [customer]"). Not
  "let me know if you're interested".

═══════════════════════════════════════════════════════════════════
FORMAT
═══════════════════════════════════════════════════════════════════

- 110–180 words in the body. No more.
- No emoji. No exclamation marks.
- Banned openers: "Hope this finds you well", "I wanted to reach
  out", "I came across your post".
- Subject line: ≤ 6 words, lowercase first word, no marketing
  words.

Return JSON { subject, body }. Body is a complete email with
salutation + sign-off. Do NOT include "Subject:" inside the body.`;

type WebsiteIdentity = {
  url: string | null;
  text: string;
};

async function fetchWebsiteIdentity(collectionName: string): Promise<WebsiteIdentity | null> {
  // The cr_agent auto-ingest writes a single brand_guide doc with
  // filename "auto-company-profile" and metadata { is_cr_agent: "true",
  // company_url: <url> }. That doc is the canonical "who you are"
  // anchor — pulled straight from the website the user submitted in
  // Frame 1 and confirmed in Frame 3.
  const matches = await listDocuments({
    collectionName,
    filter: { doc_type: "brand_guide", is_cr_agent: "true" },
    limit: 1,
  });
  if (matches.length === 0) return null;
  const doc = matches[0];
  const url = doc.metadata.company_url ? String(doc.metadata.company_url) : null;
  try {
    const content = await getDocumentContent(collectionName, doc.path);
    return { url, text: (content ?? "").slice(0, 3_000) };
  } catch {
    return { url, text: "" };
  }
}

async function fetchSupplementaryContext(params: {
  collectionName: string;
}): Promise<{ snippets: Array<{ label: string; text: string }>; evidence: string[] }> {
  // All brand-context docs EXCEPT the cr_agent identity doc (rendered
  // separately as YOUR COMPANY). No rerank — Gemma reads everything and
  // picks the most relevant evidence itself in the prompt.
  const all = await listDocuments({
    collectionName: params.collectionName,
    filter: {
      doc_type: { $in: ["brand_guide", "won_deal", "icp", "case_study", "competitor_intel"] },
    },
    limit: MAX_GROUNDING_DOCS,
  });

  const supplementary = all.filter(
    (d) => String(d.metadata.is_cr_agent ?? "") !== "true",
  );
  if (supplementary.length === 0) return { snippets: [], evidence: [] };

  const snippets: Array<{ label: string; text: string }> = [];
  const evidence: string[] = [];
  await Promise.all(
    supplementary.map(async (d) => {
      const label = String(d.metadata.filename ?? d.metadata.story_name ?? d.metadata.doc_type ?? "doc");
      try {
        const content = await getDocumentContent(params.collectionName, d.path);
        if (content && content.trim().length > 20) {
          snippets.push({
            label,
            text: content.replace(/\s+/g, " ").trim().slice(0, MAX_GROUNDING_CHARS_PER_DOC),
          });
          evidence.push(label);
        }
      } catch {
        // skip
      }
    }),
  );

  return { snippets, evidence };
}

export async function generateDraft(params: {
  collectionName: string;
  signal: SignalInfo;
}): Promise<GeneratedDraft> {
  const [identity, { snippets, evidence }] = await Promise.all([
    fetchWebsiteIdentity(params.collectionName),
    fetchSupplementaryContext({ collectionName: params.collectionName }),
  ]);

  const apiKey = process.env.GOOGLE_GENAI_API_KEY;
  if (!apiKey) return templateDraft(params.signal, evidence);

  const genai = new GoogleGenerativeAI(apiKey);
  // Mirror researchClient.ts model strategy: default to gemma-4-31b-it
  // (open-source, unlimited daily, 15 RPM). Override via GEMINI_MODEL for
  // paid Gemini access.
  const modelName = process.env.GEMINI_MODEL || "gemma-4-31b-it";
  const isGemma = modelName.toLowerCase().startsWith("gemma");
  const model = genai.getGenerativeModel({
    model: modelName,
    generationConfig: isGemma
      ? { temperature: 0.6 }
      : {
          responseMimeType: "application/json",
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          responseSchema: DRAFT_SCHEMA as any,
          temperature: 0.6,
        },
  });

  const websiteBlock = identity
    ? [
        identity.url ? `Website URL: ${identity.url}` : "",
        identity.text || "(no website summary available)",
      ]
        .filter(Boolean)
        .join("\n\n")
    : "(no website identity was captured during onboarding — infer a neutral B2B identity from the signal alone)";

  const supplementaryBlock =
    snippets.length === 0
      ? "(no supplementary documents — rely on the YOUR COMPANY section above)"
      : snippets
          .map((s, i) => `--- doc #${i + 1}: ${s.label} ---\n${s.text}`)
          .join("\n\n");

  const userPrompt = [
    SYSTEM_PROMPT,
    "",
    "## YOUR COMPANY (FROM WEBSITE) — IDENTITY ANCHOR",
    "This came from the website URL you entered during onboarding.",
    "The sign-off MUST be derived from this section.",
    "",
    websiteBlock,
    "",
    "## SUPPLEMENTARY CONTEXT (uploaded docs — extra past wins, voice samples)",
    "Use these for facts and tone, NOT for the sign-off identity.",
    "",
    supplementaryBlock,
    "",
    "## SIGNAL POST",
    `Source: ${params.signal.source}`,
    `Author handle: ${params.signal.handle}`,
    params.signal.context ? `Context: ${params.signal.context}` : "",
    `Body: ${params.signal.body}`,
    "",
    "## RECIPIENT",
    `Name: ${params.signal.contact_name}`,
    params.signal.contact_role ? `Role: ${params.signal.contact_role}` : "",
    params.signal.contact_company ? `Company: ${params.signal.contact_company}` : "",
    "",
    isGemma
      ? 'Respond with ONLY a single JSON object matching this shape (no markdown, no prose, no code fences):\n{ "subject": string, "body": string }\n\nNow write the email.'
      : "Now write the email. Return strictly { subject, body }.",
  ]
    .filter(Boolean)
    .join("\n")
    .slice(0, TOTAL_PROMPT_CAP);

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), GEMINI_TIMEOUT_MS);
  try {
    const result = await model.generateContent(userPrompt);
    const text = result.response.text();
    let parsed: { subject?: unknown; body?: unknown };
    try {
      parsed = extractJsonObject(text) as { subject?: unknown; body?: unknown };
    } catch (parseErr) {
      console.error(`[draftLLM] JSON parse failed for model=${modelName}. Raw (first 1500 chars):`);
      console.error(text.slice(0, 1500));
      throw parseErr;
    }
    const subject = typeof parsed.subject === "string" ? parsed.subject.trim() : "";
    const body = typeof parsed.body === "string" ? parsed.body.trim() : "";
    if (!subject || !body) {
      return { ...templateDraft(params.signal, evidence), fallback_reason: "empty fields in LLM response" };
    }
    return { subject, body, evidence, source: "gemini" };
  } catch (err) {
    const reason = err instanceof Error ? err.message : "unknown error";
    return { ...templateDraft(params.signal, evidence), fallback_reason: `gemini error: ${reason}` };
  } finally {
    clearTimeout(timer);
  }
}
